//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System; 
using System.ComponentModel;
using System.ComponentModel.DataAnnotations; 
using System.Data;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SO.LocalClub.Manager.Models.ValueObjects
{
    [Table("Admin", Schema = "data" )]
    [Serializable]
    public  class AdminVo
    {
    	[DisplayName("admin Id")]
    	[Required]
    	[Key]
        public int adminId { get; set; }
    
    	[DisplayName("first Name")]
    	[StringLength(50)]
        public string firstName { get; set; }
    
    	[DisplayName("last Name")]
    	[StringLength(50)]
        public string lastName { get; set; }
    
    	[DisplayName("email")]
    	[Required]
    	[StringLength(50)]
        public string email { get; set; }
    
    	[DisplayName("password")]
    	[Required]
    	[StringLength(200)]
        public string password { get; set; }
    
    	[DisplayName("is Active")]
    	[Required]
        public byte isActive { get; set; }
    
    	[DisplayName("modified")]
    	[Required]
        public DateTime modified { get; set; }
    
    	[DisplayName("created")]
    	[Required]
        public DateTime created { get; set; }
    
    }
    
}
