//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SO.LocalClub.CodeGeneration.Model.DefaultTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public System.Guid blogId { get; set; }
        public Nullable<int> clubCategoryTypeId { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string author { get; set; }
        public string url { get; set; }
        public string website { get; set; }
        public string rssUrl { get; set; }
        public string rssCommentUrl { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public Nullable<System.DateTime> created { get; set; }
    
        public virtual ClubCategoryType ClubCategoryType { get; set; }
    }
}
