//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System; 
using System.ComponentModel;
using System.ComponentModel.DataAnnotations; 
using System.Data;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SO.LocalClub.Manager.Models.ValueObjects
{
    [Table("Blog", Schema = "data" )]
    [Serializable]
    public  class BlogVo
    {
    	[DisplayName("blog Id")]
    	[Required]
    	[Key]
        public Guid blogId { get; set; }
    
    	[DisplayName("club Category Type Id")]
        public Nullable<int> clubCategoryTypeId { get; set; }
    
    	[DisplayName("name")]
    	[StringLength(150)]
        public string name { get; set; }
    
    	[DisplayName("description")]
        public string description { get; set; }
    
    	[DisplayName("author")]
    	[StringLength(50)]
        public string author { get; set; }
    
    	[DisplayName("url")]
    	[StringLength(50)]
        public string url { get; set; }
    
    	[DisplayName("website")]
    	[StringLength(50)]
        public string website { get; set; }
    
    	[DisplayName("rss Url")]
        public string rssUrl { get; set; }
    
    	[DisplayName("rss Comment Url")]
        public string rssCommentUrl { get; set; }
    
    	[DisplayName("modified")]
        public Nullable<DateTime> modified { get; set; }
    
    	[DisplayName("created")]
        public Nullable<DateTime> created { get; set; }
    
    
        [ForeignKey("clubCategoryTypeId")]
        public ClubCategoryTypeVo clubCategoryType { get; set; }
       
    }
    
}
