//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SO.SilList.CodeGeneration.DbContexts.DefaultTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessCategory
    {
        public System.Guid businessId { get; set; }
        public int businessCategoryTypeId { get; set; }
    
        public virtual BusinessCategoryType BusinessCategoryType { get; set; }
        public virtual Business Business { get; set; }
    }
}
