//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System; 
using System.ComponentModel;
using System.ComponentModel.DataAnnotations; 
using System.Data;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SO.LocalClub.Manager.Models.ValueObjects
{
    [Table("Business", Schema = "data" )]
    [Serializable]
    public  class BusinessVo
    {
        public BusinessVo()
        {
        }
    
    	[DisplayName("business Id")]
    	[Required]
    	[Key]
        public Guid businessId { get; set; }
    
    	[DisplayName("company")]
    	[StringLength(50)]
        public string company { get; set; }
    
    	[DisplayName("name")]
    	[StringLength(50)]
        public string name { get; set; }
    
    	[DisplayName("contact")]
    	[StringLength(50)]
        public string contact { get; set; }
    
    	[DisplayName("address")]
    	[StringLength(50)]
        public string address { get; set; }
    
    	[DisplayName("city")]
    	[StringLength(50)]
        public string city { get; set; }
    
    	[DisplayName("state")]
    	[StringLength(50)]
        public string state { get; set; }
    
    	[DisplayName("zip")]
        public Nullable<int> zip { get; set; }
    
    	[DisplayName("phone")]
    	[StringLength(50)]
        public string phone { get; set; }
    
    	[DisplayName("modified")]
    	[Required]
        public DateTime modified { get; set; }
    
    	[DisplayName("created")]
    	[Required]
        public DateTime created { get; set; }
    
    
        [Association("Business_Sponsor", "businessId", "businessId")]
        public List<SponsorVo> sponsors { get; set; }
       
    }
    
}
