//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System; 
using System.ComponentModel;
using System.ComponentModel.DataAnnotations; 
using System.Data;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SO.LocalClub.Manager.Models.ValueObjects
{
    [Table("City", Schema = "data" )]
    [Serializable]
    public  class CityVo
    {
        public CityVo()
        {
        }
    
    	[DisplayName("city Id")]
    	[Required]
    	[Key]
        public int cityId { get; set; }
    
    	[DisplayName("city1")]
    	[Required]
    	[StringLength(50)]
        public string city1 { get; set; }
    
    	[DisplayName("state")]
    	[StringLength(20)]
        public string state { get; set; }
    
    	[DisplayName("state Code")]
    	[StringLength(2)]
        public string stateCode { get; set; }
    
    	[DisplayName("zip")]
        public Nullable<int> zip { get; set; }
    
    	[DisplayName("county")]
    	[StringLength(50)]
        public string county { get; set; }
    
    	[DisplayName("country")]
    	[StringLength(50)]
        public string country { get; set; }
    
    	[DisplayName("modified")]
    	[Required]
        public DateTime modified { get; set; }
    
    	[DisplayName("created")]
    	[Required]
        public DateTime created { get; set; }
    
    
        [ForeignKey("zipCodeId")]
        public ZipCodeVo zipCode { get; set; }
       
        [Association("City_Club", "cityId", "cityId")]
        public List<ClubVo> clubs { get; set; }
       
    }
    
}
