//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SO.LocalClub.CodeGeneration.Model.DefaultTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Clubs = new HashSet<Club>();
        }
    
        public int cityId { get; set; }
        public string city1 { get; set; }
        public string state { get; set; }
        public string stateCode { get; set; }
        public Nullable<int> zip { get; set; }
        public string county { get; set; }
        public string country { get; set; }
        public System.DateTime modified { get; set; }
        public System.DateTime created { get; set; }
    
        public virtual ZipCode ZipCode { get; set; }
        public virtual ICollection<Club> Clubs { get; set; }
    }
}
