//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System; 
using System.ComponentModel;
using System.ComponentModel.DataAnnotations; 
using System.Data;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SO.LocalClub.Manager.Models.ValueObjects
{
    [Table("Club", Schema = "data" )]
    [Serializable]
    public  class ClubVo
    {
        public ClubVo()
        {
        }
    
    	[DisplayName("club Id")]
    	[Required]
    	[Key]
        public Guid clubId { get; set; }
    
    	[DisplayName("name")]
    	[StringLength(100)]
        public string name { get; set; }
    
    	[DisplayName("url")]
    	[StringLength(200)]
        public string url { get; set; }
    
    	[DisplayName("description")]
        public string description { get; set; }
    
    	[DisplayName("city Id")]
        public Nullable<int> cityId { get; set; }
    
    	[DisplayName("club Category Type Id")]
        public Nullable<int> clubCategoryTypeId { get; set; }
    
    	[DisplayName("modified")]
    	[Required]
        public DateTime modified { get; set; }
    
    	[DisplayName("created")]
    	[Required]
        public DateTime created { get; set; }
    
    
        [ForeignKey("cityId")]
        public CityVo city { get; set; }
       
        [ForeignKey("clubCategoryTypeId")]
        public ClubCategoryTypeVo clubCategoryType { get; set; }
       
        [Association("Club_ClubEvent", "clubId", "clubId")]
        public List<ClubEventVo> clubEvents { get; set; }
       
        [Association("Club_ClubMember", "clubId", "clubId")]
        public List<ClubMemberVo> clubMembers { get; set; }
       
        [Association("Club_Discussion", "clubId", "clubId")]
        public List<DiscussionVo> discussions { get; set; }
       
    }
    
}
