//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System; 
using System.ComponentModel;
using System.ComponentModel.DataAnnotations; 
using System.Data;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SO.LocalClub.Manager.Models.ValueObjects
{
    [Table("ClubMemberRoleType", Schema = "data" )]
    [Serializable]
    public  class ClubMemberRoleTypeVo
    {
        public ClubMemberRoleTypeVo()
        {
        }
    
    	[DisplayName("club Member Role Type Id")]
    	[Required]
    	[Key]
        public int clubMemberRoleTypeId { get; set; }
    
    	[DisplayName("name")]
    	[Required]
    	[StringLength(50)]
        public string name { get; set; }
    
    	[DisplayName("modified")]
    	[Required]
        public DateTime modified { get; set; }
    
    	[DisplayName("created")]
    	[Required]
        public DateTime created { get; set; }
    
    
        [Association("ClubMemberRoleType_ClubMember", "clubMemberRoleTypeId", "clubMemberRoleTypeId")]
        public List<ClubMemberVo> clubMembers { get; set; }
       
    }
    
}
