//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SO.LocalClub.CodeGeneration.Model.DefaultTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClubCategoryType
    {
        public ClubCategoryType()
        {
            this.Blogs = new HashSet<Blog>();
            this.Clubs = new HashSet<Club>();
        }
    
        public int clubCategoryTypeId { get; set; }
        public string name { get; set; }
        public int parentId { get; set; }
        public System.DateTime modified { get; set; }
        public System.DateTime created { get; set; }
    
        public virtual ICollection<Blog> Blogs { get; set; }
        public virtual ICollection<Club> Clubs { get; set; }
    }
}
