//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SO.LocalClub.CodeGeneration.Model.DefaultTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClubMember
    {
        public System.Guid clubMemberId { get; set; }
        public Nullable<System.Guid> clubId { get; set; }
        public Nullable<System.Guid> memberId { get; set; }
        public Nullable<int> clubMemberRoleTypeId { get; set; }
        public System.DateTime modified { get; set; }
        public System.DateTime created { get; set; }
    
        public virtual ClubMemberRoleType ClubMemberRoleType { get; set; }
        public virtual Club Club { get; set; }
        public virtual Member Member { get; set; }
    }
}
