//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System; 
using System.ComponentModel;
using System.ComponentModel.DataAnnotations; 
using System.Data;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SO.LocalClub.Manager.Models.ValueObjects
{
    [Table("ClubMember", Schema = "data" )]
    [Serializable]
    public  class ClubMemberVo
    {
    	[DisplayName("club Member Id")]
    	[Required]
    	[Key]
        public Guid clubMemberId { get; set; }
    
    	[DisplayName("club Id")]
        public Nullable<Guid> clubId { get; set; }
    
    	[DisplayName("member Id")]
        public Nullable<Guid> memberId { get; set; }
    
    	[DisplayName("club Member Role Type Id")]
        public Nullable<int> clubMemberRoleTypeId { get; set; }
    
    	[DisplayName("modified")]
    	[Required]
        public DateTime modified { get; set; }
    
    	[DisplayName("created")]
    	[Required]
        public DateTime created { get; set; }
    
    
        [ForeignKey("clubMemberRoleTypeId")]
        public ClubMemberRoleTypeVo clubMemberRoleType { get; set; }
       
        [ForeignKey("clubId")]
        public ClubVo club { get; set; }
       
        [ForeignKey("memberId")]
        public MemberVo member { get; set; }
       
    }
    
}
