//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System; 
using System.ComponentModel;
using System.ComponentModel.DataAnnotations; 
using System.Data;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SO.LocalClub.Manager.Models.ValueObjects
{
    [Table("ClubCategoryType", Schema = "data" )]
    [Serializable]
    public  class ClubCategoryTypeVo
    {
        public ClubCategoryTypeVo()
        {
        }
    
    	[DisplayName("club Category Type Id")]
    	[Required]
    	[Key]
        public int clubCategoryTypeId { get; set; }
    
    	[DisplayName("name")]
    	[StringLength(50)]
        public string name { get; set; }
    
    	[DisplayName("parent Id")]
    	[Required]
        public int parentId { get; set; }
    
    	[DisplayName("modified")]
    	[Required]
        public DateTime modified { get; set; }
    
    	[DisplayName("created")]
    	[Required]
        public DateTime created { get; set; }
    
    
        [Association("ClubCategoryType_Blog", "clubCategoryTypeId", "clubCategoryTypeId")]
        public List<BlogVo> blogs { get; set; }
       
        [Association("ClubCategoryType_Club", "clubCategoryTypeId", "clubCategoryTypeId")]
        public List<ClubVo> clubs { get; set; }
       
    }
    
}
