//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SO.LocalClub.CodeGeneration.Model.DefaultTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClubEventMember
    {
        public System.Guid clubEventMemberId { get; set; }
        public System.Guid memberId { get; set; }
        public System.Guid clubEventId { get; set; }
        public Nullable<byte> isGoing { get; set; }
        public string comment { get; set; }
        public System.DateTime modified { get; set; }
        public System.DateTime created { get; set; }
    
        public virtual ClubEvent ClubEvent { get; set; }
        public virtual Member Member { get; set; }
    }
}
