//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SO.LocalClub.CodeGeneration.Model.DefaultTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClubEvent
    {
        public ClubEvent()
        {
            this.ClubEventMembers = new HashSet<ClubEventMember>();
        }
    
        public System.Guid clubEventId { get; set; }
        public System.Guid clubId { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.Guid> leaderId { get; set; }
        public System.DateTime modified { get; set; }
        public System.DateTime created { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual ICollection<ClubEventMember> ClubEventMembers { get; set; }
        public virtual Member Member { get; set; }
    }
}
