//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SO.LocalClub.CodeGeneration.Model.DefaultTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discussion
    {
        public Discussion()
        {
            this.DiscussionMessages = new HashSet<DiscussionMessage>();
        }
    
        public System.Guid discussionId { get; set; }
        public string name { get; set; }
        public System.Guid clubId { get; set; }
        public System.Guid createdBy { get; set; }
        public System.DateTime modified { get; set; }
        public System.DateTime created { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual ICollection<DiscussionMessage> DiscussionMessages { get; set; }
    }
}
