//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System; 
using System.ComponentModel;
using System.ComponentModel.DataAnnotations; 
using System.Data;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SO.LocalClub.Manager.Models.ValueObjects
{
    [Table("Discussion", Schema = "data" )]
    [Serializable]
    public  class DiscussionVo
    {
        public DiscussionVo()
        {
        }
    
    	[DisplayName("discussion Id")]
    	[Required]
    	[Key]
        public Guid discussionId { get; set; }
    
    	[DisplayName("name")]
    	[Required]
        public string name { get; set; }
    
    	[DisplayName("club Id")]
    	[Required]
        public Guid clubId { get; set; }
    
    	[DisplayName("created By")]
    	[Required]
        public Guid createdBy { get; set; }
    
    	[DisplayName("modified")]
    	[Required]
        public DateTime modified { get; set; }
    
    	[DisplayName("created")]
    	[Required]
        public DateTime created { get; set; }
    
    
        [ForeignKey("clubId")]
        public ClubVo club { get; set; }
       
        [Association("Discussion_DiscussionMessage", "discussionId", "discussionId")]
        public List<DiscussionMessageVo> discussionMessages { get; set; }
       
    }
    
}
