//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System; 
using System.ComponentModel;
using System.ComponentModel.DataAnnotations; 
using System.Data;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SO.LocalClub.Manager.Models.ValueObjects
{
    [Table("DiscussionMessage", Schema = "data" )]
    [Serializable]
    public  class DiscussionMessageVo
    {
    	[DisplayName("discussion Message Id")]
    	[Required]
    	[Key]
        public Guid discussionMessageId { get; set; }
    
    	[DisplayName("discussion Id")]
    	[Required]
        public Guid discussionId { get; set; }
    
    	[DisplayName("member Id")]
    	[Required]
        public Guid memberId { get; set; }
    
    	[DisplayName("message")]
        public string message { get; set; }
    
    	[DisplayName("modified")]
    	[Required]
        public DateTime modified { get; set; }
    
    	[DisplayName("created")]
    	[Required]
        public DateTime created { get; set; }
    
    
        [ForeignKey("discussionId")]
        public DiscussionVo discussion { get; set; }
       
    }
    
}
