//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SO.LocalClub.CodeGeneration.Model.DefaultTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberFileLink
    {
        public System.Guid memberFileLinkId { get; set; }
        public System.Guid memberId { get; set; }
        public string name { get; set; }
        public string group { get; set; }
        public string path { get; set; }
        public Nullable<byte> isProfileImage { get; set; }
        public System.DateTime modified { get; set; }
        public System.DateTime created { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
