//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SO.LocalClub.CodeGeneration.Model.DefaultTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.ClubEventMembers = new HashSet<ClubEventMember>();
            this.ClubEvents = new HashSet<ClubEvent>();
            this.ClubMembers = new HashSet<ClubMember>();
            this.MemberFileLinks = new HashSet<MemberFileLink>();
        }
    
        public System.Guid memberId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public int zip { get; set; }
        public Nullable<int> cityId { get; set; }
        public bool isEmailConfirmed { get; set; }
        public bool isActive { get; set; }
        public System.DateTime modified { get; set; }
        public System.DateTime created { get; set; }
    
        public virtual ICollection<ClubEventMember> ClubEventMembers { get; set; }
        public virtual ICollection<ClubEvent> ClubEvents { get; set; }
        public virtual ICollection<ClubMember> ClubMembers { get; set; }
        public virtual ICollection<MemberFileLink> MemberFileLinks { get; set; }
    }
}
