//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System; 
using System.ComponentModel;
using System.ComponentModel.DataAnnotations; 
using System.Data;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SO.LocalClub.Manager.Models.ValueObjects
{
    [Table("MemberFileLink", Schema = "data" )]
    [Serializable]
    public  class MemberFileLinkVo
    {
    	[DisplayName("member File Link Id")]
    	[Required]
    	[Key]
        public Guid memberFileLinkId { get; set; }
    
    	[DisplayName("member Id")]
    	[Required]
        public Guid memberId { get; set; }
    
    	[DisplayName("name")]
    	[StringLength(50)]
        public string name { get; set; }
    
    	[DisplayName("group")]
    	[StringLength(50)]
        public string group { get; set; }
    
    	[DisplayName("path")]
    	[StringLength(200)]
        public string path { get; set; }
    
    	[DisplayName("is Profile Image")]
        public Nullable<byte> isProfileImage { get; set; }
    
    	[DisplayName("modified")]
    	[Required]
        public DateTime modified { get; set; }
    
    	[DisplayName("created")]
    	[Required]
        public DateTime created { get; set; }
    
    
        [ForeignKey("memberId")]
        public MemberVo member { get; set; }
       
    }
    
}
