//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace SO.LocalClub.Manager.DbContexts
{
    public partial class LocalClubEntities : DbContext
    {
        public LocalClubEntities()
            : base("name=LocalClubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
        }
    
        public DbSet<AdminVo> admins { get; set; }
        public DbSet<CityVo> cities { get; set; }
        public DbSet<ClubCategoryTypeVo> clubCategoryTypes { get; set; }
        public DbSet<ClubMemberRoleTypeVo> clubMemberRoleTypes { get; set; }
        public DbSet<ZipCodeVo> zipCodes { get; set; }
        public DbSet<BlogVo> blogs { get; set; }
        public DbSet<BusinessVo> businesses { get; set; }
        public DbSet<ClubVo> clubs { get; set; }
        public DbSet<ClubEventMemberVo> clubEventMembers { get; set; }
        public DbSet<ClubEventVo> clubEvents { get; set; }
        public DbSet<ClubMemberVo> clubMembers { get; set; }
        public DbSet<DiscussionVo> discussions { get; set; }
        public DbSet<DiscussionMessageVo> discussionMessages { get; set; }
        public DbSet<MemberFileLinkVo> memberFileLinks { get; set; }
        public DbSet<SponsorVo> sponsors { get; set; }
        public DbSet<MemberVo> members { get; set; }
    }
}
