//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System; 
using System.ComponentModel;
using System.ComponentModel.DataAnnotations; 
using System.Data;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SO.LocalClub.Manager.Models.ValueObjects
{
    [Table("ZipCode", Schema = "data" )]
    [Serializable]
    public  class ZipCodeVo
    {
        public ZipCodeVo()
        {
        }
    
    	[DisplayName("zip")]
    	[Required]
    	[Key]
        public int zip { get; set; }
    
    	[DisplayName("latitude")]
        public Nullable<double> latitude { get; set; }
    
    	[DisplayName("longitude")]
        public Nullable<double> longitude { get; set; }
    
    	[DisplayName("modified")]
    	[Required]
        public DateTime modified { get; set; }
    
    	[DisplayName("created")]
    	[Required]
        public DateTime created { get; set; }
    
    
        [Association("ZipCode_City", "zip", "zip")]
        public List<CityVo> cities { get; set; }
       
    }
    
}
