CREATE TABLE [data].[Member]
(
	[memberId] INT NOT NULL  , 
    [siteId] INT NULL, 
    [firstName] NVARCHAR(50) NULL, 
    [lastName] NVARCHAR(50) NULL, 
    [address] NVARCHAR(50) NULL, 
    [city] NVARCHAR(50) NULL, 
    [state] NVARCHAR(50) NULL, 
    [zip] NVARCHAR(50) NULL, 
    [email] NVARCHAR(50) NULL, 
    [username] NVARCHAR(50) NULL, 
    [password] NVARCHAR(50) NULL, 
    [phone] NVARCHAR(50) NULL, 
    [isEmailConfirmed] BIT NULL DEFAULT 0, 
    [ipAddress] NVARCHAR(50) NULL, 
    [lastLogin] DATETIME NOT NULL DEFAULT getdate(), 
    [isEmailSubscribed] BIT NULL DEFAULT 0, 
    [created] DATETIME NOT NULL DEFAULT getdate(), 
    [modified] DATETIME NOT NULL DEFAULT getdate(), 
    [createdBy] INT NULL, 
    [modifiedBy] INT NULL, 
    [isActive] BIT NULL, 
    CONSTRAINT [PK_Member] PRIMARY KEY ([memberId])
)
