//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SO.SilList.CodeGeneration.DbContexts.SilList
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business
    {
        public Business()
        {
            this.BusinessImages = new HashSet<BusinessImage>();
            this.BusinessRatings = new HashSet<BusinessRating>();
            this.BusinessServices = new HashSet<BusinessService>();
        }
    
        public System.Guid businessId { get; set; }
        public Nullable<int> siteId { get; set; }
        public Nullable<System.Guid> listingDetailId { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public Nullable<int> zip { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<int> modifiedBy { get; set; }
        public System.DateTime modified { get; set; }
        public System.DateTime created { get; set; }
        public bool isActive { get; set; }
    
        public virtual Site Site { get; set; }
        public virtual ListingDetail ListingDetail { get; set; }
        public virtual ICollection<BusinessImage> BusinessImages { get; set; }
        public virtual ICollection<BusinessRating> BusinessRatings { get; set; }
        public virtual ICollection<BusinessService> BusinessServices { get; set; }
    }
}
