//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SO.SilList.CodeGeneration.DbContexts.SilList
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListingCategory
    {
        public System.Guid listingCategoryId { get; set; }
        public Nullable<int> listingCategoryTypeId { get; set; }
        public Nullable<System.Guid> listingId { get; set; }
        public Nullable<int> createdBy_ { get; set; }
        public Nullable<int> modifiedBy { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime modified { get; set; }
        public bool isActive { get; set; }
    
        public virtual ListingCategoryType ListingCategoryType { get; set; }
        public virtual Listing Listing { get; set; }
    }
}
