//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SO.SilList.CodeGeneration.DbContexts.SilList
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SilListEntities8 : DbContext
    {
        public SilListEntities8()
            : base("name=SilListEntities8")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BusinessCategoryType> BusinessCategoryTypes { get; set; }
        public DbSet<JobCategory> JobCategories { get; set; }
        public DbSet<JobCategoryType> JobCategoryTypes { get; set; }
        public DbSet<JobType> JobTypes { get; set; }
        public DbSet<LeaseTermType> LeaseTermTypes { get; set; }
        public DbSet<PropertyType> PropertyTypes { get; set; }
        public DbSet<RentType> RentTypes { get; set; }
        public DbSet<ServiceType> ServiceTypes { get; set; }
        public DbSet<Site> Sites { get; set; }
        public DbSet<Business> Businesses { get; set; }
        public DbSet<BusinessCategory> BusinessCategories { get; set; }
        public DbSet<BusinessImage> BusinessImages { get; set; }
        public DbSet<BusinessRating> BusinessRatings { get; set; }
        public DbSet<BusinessService> BusinessServices { get; set; }
        public DbSet<Image> Images { get; set; }
        public DbSet<Job> Jobs { get; set; }
        public DbSet<ListingDetail> ListingDetails { get; set; }
        public DbSet<Member> Members { get; set; }
        public DbSet<Rating> Ratings { get; set; }
        public DbSet<Rental> Rentals { get; set; }
        public DbSet<RentalImage> RentalImages { get; set; }
    }
}
