//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SO.SilList.CodeGeneration.DbContexts.SilList
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SilListEntities7 : DbContext
    {
        public SilListEntities7()
            : base("name=SilListEntities7")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BusinessCategoryType> BusinessCategoryType { get; set; }
        public DbSet<JobCategories> JobCategories { get; set; }
        public DbSet<JobCategoryType> JobCategoryType { get; set; }
        public DbSet<JobType> JobType { get; set; }
        public DbSet<LeaseTermType> LeaseTermType { get; set; }
        public DbSet<PropertyType> PropertyType { get; set; }
        public DbSet<RentType> RentType { get; set; }
        public DbSet<ServiceType> ServiceType { get; set; }
        public DbSet<Site> Site { get; set; }
        public DbSet<Business> Business { get; set; }
        public DbSet<BusinessCategories> BusinessCategories { get; set; }
        public DbSet<BusinessImages> BusinessImages { get; set; }
        public DbSet<BusinessRatings> BusinessRatings { get; set; }
        public DbSet<BusinessServices> BusinessServices { get; set; }
        public DbSet<Image> Image { get; set; }
        public DbSet<Job> Job { get; set; }
        public DbSet<JobCompany> JobCompany { get; set; }
        public DbSet<ListingDetail> ListingDetail { get; set; }
        public DbSet<Member> Member { get; set; }
        public DbSet<Rating> Rating { get; set; }
        public DbSet<Rental> Rental { get; set; }
        public DbSet<RentalImages> RentalImages { get; set; }
    }
}
