//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SO.SilList.CodeGeneration.DbContexts.SilList
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public Rental()
        {
            this.RentalImages = new HashSet<RentalImage>();
        }
    
        public System.Guid rentalId { get; set; }
        public Nullable<int> propertyTypeId { get; set; }
        public Nullable<System.Guid> listingDetailId { get; set; }
        public Nullable<int> siteId { get; set; }
        public Nullable<int> bedrooms { get; set; }
        public Nullable<int> bathrooms { get; set; }
        public Nullable<double> rent { get; set; }
        public Nullable<int> leaseTermTypeId { get; set; }
        public Nullable<int> size { get; set; }
        public Nullable<int> lotSize { get; set; }
        public Nullable<bool> acceptsSection8 { get; set; }
        public Nullable<int> rentTypeId { get; set; }
        public Nullable<int> modifiedBy { get; set; }
        public System.DateTime modified { get; set; }
        public Nullable<int> createdBy { get; set; }
        public System.DateTime created { get; set; }
        public bool isActive { get; set; }
    
        public virtual LeaseTermType LeaseTermType { get; set; }
        public virtual PropertyType PropertyType { get; set; }
        public virtual RentType RentType { get; set; }
        public virtual Site Site { get; set; }
        public virtual ListingDetail ListingDetail { get; set; }
        public virtual ICollection<RentalImage> RentalImages { get; set; }
    }
}
