//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("AppDataModel1", "FK_Menu_Website", "Website", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SO.SilList.CodeGeneration.DbContexts.SilList.Website), "Menu", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SO.SilList.CodeGeneration.DbContexts.SilList.Menu), true)]
[assembly: EdmRelationshipAttribute("AppDataModel1", "FK_MenuWidget_Menu", "Menu", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SO.SilList.CodeGeneration.DbContexts.SilList.Menu), "MenuItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SO.SilList.CodeGeneration.DbContexts.SilList.MenuItem), true)]
[assembly: EdmRelationshipAttribute("AppDataModel1", "FK_Page_Website", "Website", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SO.SilList.CodeGeneration.DbContexts.SilList.Website), "Page", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SO.SilList.CodeGeneration.DbContexts.SilList.Page), true)]
[assembly: EdmRelationshipAttribute("AppDataModel1", "FK_UserRoles_Roles", "Roles", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SO.SilList.CodeGeneration.DbContexts.SilList.Role), "UserRoles", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SO.SilList.CodeGeneration.DbContexts.SilList.UserRole), true)]
[assembly: EdmRelationshipAttribute("AppDataModel1", "FK_UserRoles_Users", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SO.SilList.CodeGeneration.DbContexts.SilList.User), "UserRoles", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SO.SilList.CodeGeneration.DbContexts.SilList.UserRole), true)]
[assembly: EdmRelationshipAttribute("AppDataModel1", "FK_Website_Theme", "Theme", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SO.SilList.CodeGeneration.DbContexts.SilList.Theme), "Website", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SO.SilList.CodeGeneration.DbContexts.SilList.Website), true)]

#endregion

namespace SO.SilList.CodeGeneration.DbContexts.SilList
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AppDataEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AppDataEntities object using the connection string found in the 'AppDataEntities' section of the application configuration file.
        /// </summary>
        public AppDataEntities() : base("name=AppDataEntities", "AppDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AppDataEntities object.
        /// </summary>
        public AppDataEntities(string connectionString) : base(connectionString, "AppDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AppDataEntities object.
        /// </summary>
        public AppDataEntities(EntityConnection connection) : base(connection, "AppDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Menu> Menus
        {
            get
            {
                if ((_Menus == null))
                {
                    _Menus = base.CreateObjectSet<Menu>("Menus");
                }
                return _Menus;
            }
        }
        private ObjectSet<Menu> _Menus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MenuItem> MenuItems
        {
            get
            {
                if ((_MenuItems == null))
                {
                    _MenuItems = base.CreateObjectSet<MenuItem>("MenuItems");
                }
                return _MenuItems;
            }
        }
        private ObjectSet<MenuItem> _MenuItems;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Page> Pages
        {
            get
            {
                if ((_Pages == null))
                {
                    _Pages = base.CreateObjectSet<Page>("Pages");
                }
                return _Pages;
            }
        }
        private ObjectSet<Page> _Pages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Role> Roles
        {
            get
            {
                if ((_Roles == null))
                {
                    _Roles = base.CreateObjectSet<Role>("Roles");
                }
                return _Roles;
            }
        }
        private ObjectSet<Role> _Roles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Theme> Themes
        {
            get
            {
                if ((_Themes == null))
                {
                    _Themes = base.CreateObjectSet<Theme>("Themes");
                }
                return _Themes;
            }
        }
        private ObjectSet<Theme> _Themes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserRole> UserRoles
        {
            get
            {
                if ((_UserRoles == null))
                {
                    _UserRoles = base.CreateObjectSet<UserRole>("UserRoles");
                }
                return _UserRoles;
            }
        }
        private ObjectSet<UserRole> _UserRoles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Website> Websites
        {
            get
            {
                if ((_Websites == null))
                {
                    _Websites = base.CreateObjectSet<Website>("Websites");
                }
                return _Websites;
            }
        }
        private ObjectSet<Website> _Websites;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Menus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMenus(Menu menu)
        {
            base.AddObject("Menus", menu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MenuItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMenuItems(MenuItem menuItem)
        {
            base.AddObject("MenuItems", menuItem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPages(Page page)
        {
            base.AddObject("Pages", page);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Roles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRoles(Role role)
        {
            base.AddObject("Roles", role);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Themes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToThemes(Theme theme)
        {
            base.AddObject("Themes", theme);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserRoles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserRoles(UserRole userRole)
        {
            base.AddObject("UserRoles", userRole);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Websites EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWebsites(Website website)
        {
            base.AddObject("Websites", website);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AppDataModel1", Name="Menu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Menu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Menu object.
        /// </summary>
        /// <param name="menuId">Initial value of the menuId property.</param>
        /// <param name="parentId">Initial value of the parentId property.</param>
        /// <param name="modified">Initial value of the modified property.</param>
        /// <param name="created">Initial value of the created property.</param>
        public static Menu CreateMenu(global::System.Int32 menuId, global::System.Int32 parentId, global::System.DateTime modified, global::System.DateTime created)
        {
            Menu menu = new Menu();
            menu.menuId = menuId;
            menu.parentId = parentId;
            menu.modified = modified;
            menu.created = created;
            return menu;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 menuId
        {
            get
            {
                return _menuId;
            }
            set
            {
                if (_menuId != value)
                {
                    OnmenuIdChanging(value);
                    ReportPropertyChanging("menuId");
                    _menuId = StructuralObject.SetValidValue(value, "menuId");
                    ReportPropertyChanged("menuId");
                    OnmenuIdChanged();
                }
            }
        }
        private global::System.Int32 _menuId;
        partial void OnmenuIdChanging(global::System.Int32 value);
        partial void OnmenuIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> websiteId
        {
            get
            {
                return _websiteId;
            }
            set
            {
                OnwebsiteIdChanging(value);
                ReportPropertyChanging("websiteId");
                _websiteId = StructuralObject.SetValidValue(value, "websiteId");
                ReportPropertyChanged("websiteId");
                OnwebsiteIdChanged();
            }
        }
        private Nullable<global::System.Int32> _websiteId;
        partial void OnwebsiteIdChanging(Nullable<global::System.Int32> value);
        partial void OnwebsiteIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 parentId
        {
            get
            {
                return _parentId;
            }
            set
            {
                OnparentIdChanging(value);
                ReportPropertyChanging("parentId");
                _parentId = StructuralObject.SetValidValue(value, "parentId");
                ReportPropertyChanged("parentId");
                OnparentIdChanged();
            }
        }
        private global::System.Int32 _parentId;
        partial void OnparentIdChanging(global::System.Int32 value);
        partial void OnparentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime modified
        {
            get
            {
                return _modified;
            }
            set
            {
                OnmodifiedChanging(value);
                ReportPropertyChanging("modified");
                _modified = StructuralObject.SetValidValue(value, "modified");
                ReportPropertyChanged("modified");
                OnmodifiedChanged();
            }
        }
        private global::System.DateTime _modified;
        partial void OnmodifiedChanging(global::System.DateTime value);
        partial void OnmodifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime created
        {
            get
            {
                return _created;
            }
            set
            {
                OncreatedChanging(value);
                ReportPropertyChanging("created");
                _created = StructuralObject.SetValidValue(value, "created");
                ReportPropertyChanged("created");
                OncreatedChanged();
            }
        }
        private global::System.DateTime _created;
        partial void OncreatedChanging(global::System.DateTime value);
        partial void OncreatedChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AppDataModel1", "FK_Menu_Website", "Website")]
        public Website Website
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Website>("AppDataModel1.FK_Menu_Website", "Website").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Website>("AppDataModel1.FK_Menu_Website", "Website").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Website> WebsiteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Website>("AppDataModel1.FK_Menu_Website", "Website");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Website>("AppDataModel1.FK_Menu_Website", "Website", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AppDataModel1", "FK_MenuWidget_Menu", "MenuItem")]
        public EntityCollection<MenuItem> MenuItems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MenuItem>("AppDataModel1.FK_MenuWidget_Menu", "MenuItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MenuItem>("AppDataModel1.FK_MenuWidget_Menu", "MenuItem", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AppDataModel1", Name="MenuItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MenuItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MenuItem object.
        /// </summary>
        /// <param name="menuItem1">Initial value of the menuItem1 property.</param>
        public static MenuItem CreateMenuItem(global::System.Int32 menuItem1)
        {
            MenuItem menuItem = new MenuItem();
            menuItem.menuItem1 = menuItem1;
            return menuItem;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 menuItem1
        {
            get
            {
                return _menuItem1;
            }
            set
            {
                if (_menuItem1 != value)
                {
                    OnmenuItem1Changing(value);
                    ReportPropertyChanging("menuItem1");
                    _menuItem1 = StructuralObject.SetValidValue(value, "menuItem1");
                    ReportPropertyChanged("menuItem1");
                    OnmenuItem1Changed();
                }
            }
        }
        private global::System.Int32 _menuItem1;
        partial void OnmenuItem1Changing(global::System.Int32 value);
        partial void OnmenuItem1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> menuId
        {
            get
            {
                return _menuId;
            }
            set
            {
                OnmenuIdChanging(value);
                ReportPropertyChanging("menuId");
                _menuId = StructuralObject.SetValidValue(value, "menuId");
                ReportPropertyChanged("menuId");
                OnmenuIdChanged();
            }
        }
        private Nullable<global::System.Int32> _menuId;
        partial void OnmenuIdChanging(Nullable<global::System.Int32> value);
        partial void OnmenuIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String menuItemType
        {
            get
            {
                return _menuItemType;
            }
            set
            {
                OnmenuItemTypeChanging(value);
                ReportPropertyChanging("menuItemType");
                _menuItemType = StructuralObject.SetValidValue(value, true, "menuItemType");
                ReportPropertyChanged("menuItemType");
                OnmenuItemTypeChanged();
            }
        }
        private global::System.String _menuItemType;
        partial void OnmenuItemTypeChanging(global::System.String value);
        partial void OnmenuItemTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String link
        {
            get
            {
                return _link;
            }
            set
            {
                OnlinkChanging(value);
                ReportPropertyChanging("link");
                _link = StructuralObject.SetValidValue(value, true, "link");
                ReportPropertyChanged("link");
                OnlinkChanged();
            }
        }
        private global::System.String _link;
        partial void OnlinkChanging(global::System.String value);
        partial void OnlinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String target
        {
            get
            {
                return _target;
            }
            set
            {
                OntargetChanging(value);
                ReportPropertyChanging("target");
                _target = StructuralObject.SetValidValue(value, true, "target");
                ReportPropertyChanged("target");
                OntargetChanged();
            }
        }
        private global::System.String _target;
        partial void OntargetChanging(global::System.String value);
        partial void OntargetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String query
        {
            get
            {
                return _query;
            }
            set
            {
                OnqueryChanging(value);
                ReportPropertyChanging("query");
                _query = StructuralObject.SetValidValue(value, true, "query");
                ReportPropertyChanged("query");
                OnqueryChanged();
            }
        }
        private global::System.String _query;
        partial void OnqueryChanging(global::System.String value);
        partial void OnqueryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> modified
        {
            get
            {
                return _modified;
            }
            set
            {
                OnmodifiedChanging(value);
                ReportPropertyChanging("modified");
                _modified = StructuralObject.SetValidValue(value, "modified");
                ReportPropertyChanged("modified");
                OnmodifiedChanged();
            }
        }
        private Nullable<global::System.DateTime> _modified;
        partial void OnmodifiedChanging(Nullable<global::System.DateTime> value);
        partial void OnmodifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> created
        {
            get
            {
                return _created;
            }
            set
            {
                OncreatedChanging(value);
                ReportPropertyChanging("created");
                _created = StructuralObject.SetValidValue(value, "created");
                ReportPropertyChanged("created");
                OncreatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _created;
        partial void OncreatedChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AppDataModel1", "FK_MenuWidget_Menu", "Menu")]
        public Menu Menu
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Menu>("AppDataModel1.FK_MenuWidget_Menu", "Menu").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Menu>("AppDataModel1.FK_MenuWidget_Menu", "Menu").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Menu> MenuReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Menu>("AppDataModel1.FK_MenuWidget_Menu", "Menu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Menu>("AppDataModel1.FK_MenuWidget_Menu", "Menu", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AppDataModel1", Name="Page")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Page : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Page object.
        /// </summary>
        /// <param name="pageId">Initial value of the pageId property.</param>
        /// <param name="published">Initial value of the published property.</param>
        /// <param name="modified">Initial value of the modified property.</param>
        /// <param name="created">Initial value of the created property.</param>
        public static Page CreatePage(global::System.Int32 pageId, global::System.Byte published, global::System.DateTime modified, global::System.DateTime created)
        {
            Page page = new Page();
            page.pageId = pageId;
            page.published = published;
            page.modified = modified;
            page.created = created;
            return page;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pageId
        {
            get
            {
                return _pageId;
            }
            set
            {
                if (_pageId != value)
                {
                    OnpageIdChanging(value);
                    ReportPropertyChanging("pageId");
                    _pageId = StructuralObject.SetValidValue(value, "pageId");
                    ReportPropertyChanged("pageId");
                    OnpageIdChanged();
                }
            }
        }
        private global::System.Int32 _pageId;
        partial void OnpageIdChanging(global::System.Int32 value);
        partial void OnpageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> websiteId
        {
            get
            {
                return _websiteId;
            }
            set
            {
                OnwebsiteIdChanging(value);
                ReportPropertyChanging("websiteId");
                _websiteId = StructuralObject.SetValidValue(value, "websiteId");
                ReportPropertyChanged("websiteId");
                OnwebsiteIdChanged();
            }
        }
        private Nullable<global::System.Int32> _websiteId;
        partial void OnwebsiteIdChanging(Nullable<global::System.Int32> value);
        partial void OnwebsiteIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true, "title");
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String content
        {
            get
            {
                return _content;
            }
            set
            {
                OncontentChanging(value);
                ReportPropertyChanging("content");
                _content = StructuralObject.SetValidValue(value, true, "content");
                ReportPropertyChanged("content");
                OncontentChanged();
            }
        }
        private global::System.String _content;
        partial void OncontentChanging(global::System.String value);
        partial void OncontentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte published
        {
            get
            {
                return _published;
            }
            set
            {
                OnpublishedChanging(value);
                ReportPropertyChanging("published");
                _published = StructuralObject.SetValidValue(value, "published");
                ReportPropertyChanged("published");
                OnpublishedChanged();
            }
        }
        private global::System.Byte _published;
        partial void OnpublishedChanging(global::System.Byte value);
        partial void OnpublishedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime modified
        {
            get
            {
                return _modified;
            }
            set
            {
                OnmodifiedChanging(value);
                ReportPropertyChanging("modified");
                _modified = StructuralObject.SetValidValue(value, "modified");
                ReportPropertyChanged("modified");
                OnmodifiedChanged();
            }
        }
        private global::System.DateTime _modified;
        partial void OnmodifiedChanging(global::System.DateTime value);
        partial void OnmodifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime created
        {
            get
            {
                return _created;
            }
            set
            {
                OncreatedChanging(value);
                ReportPropertyChanging("created");
                _created = StructuralObject.SetValidValue(value, "created");
                ReportPropertyChanged("created");
                OncreatedChanged();
            }
        }
        private global::System.DateTime _created;
        partial void OncreatedChanging(global::System.DateTime value);
        partial void OncreatedChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AppDataModel1", "FK_Page_Website", "Website")]
        public Website Website
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Website>("AppDataModel1.FK_Page_Website", "Website").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Website>("AppDataModel1.FK_Page_Website", "Website").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Website> WebsiteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Website>("AppDataModel1.FK_Page_Website", "Website");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Website>("AppDataModel1.FK_Page_Website", "Website", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AppDataModel1", Name="Role")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Role : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Role object.
        /// </summary>
        /// <param name="roleId">Initial value of the roleId property.</param>
        /// <param name="modified">Initial value of the modified property.</param>
        /// <param name="created">Initial value of the created property.</param>
        public static Role CreateRole(global::System.Int32 roleId, global::System.DateTime modified, global::System.DateTime created)
        {
            Role role = new Role();
            role.roleId = roleId;
            role.modified = modified;
            role.created = created;
            return role;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 roleId
        {
            get
            {
                return _roleId;
            }
            set
            {
                if (_roleId != value)
                {
                    OnroleIdChanging(value);
                    ReportPropertyChanging("roleId");
                    _roleId = StructuralObject.SetValidValue(value, "roleId");
                    ReportPropertyChanged("roleId");
                    OnroleIdChanged();
                }
            }
        }
        private global::System.Int32 _roleId;
        partial void OnroleIdChanging(global::System.Int32 value);
        partial void OnroleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true, "description");
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime modified
        {
            get
            {
                return _modified;
            }
            set
            {
                OnmodifiedChanging(value);
                ReportPropertyChanging("modified");
                _modified = StructuralObject.SetValidValue(value, "modified");
                ReportPropertyChanged("modified");
                OnmodifiedChanged();
            }
        }
        private global::System.DateTime _modified;
        partial void OnmodifiedChanging(global::System.DateTime value);
        partial void OnmodifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime created
        {
            get
            {
                return _created;
            }
            set
            {
                OncreatedChanging(value);
                ReportPropertyChanging("created");
                _created = StructuralObject.SetValidValue(value, "created");
                ReportPropertyChanged("created");
                OncreatedChanged();
            }
        }
        private global::System.DateTime _created;
        partial void OncreatedChanging(global::System.DateTime value);
        partial void OncreatedChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AppDataModel1", "FK_UserRoles_Roles", "UserRoles")]
        public EntityCollection<UserRole> UserRoles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserRole>("AppDataModel1.FK_UserRoles_Roles", "UserRoles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserRole>("AppDataModel1.FK_UserRoles_Roles", "UserRoles", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AppDataModel1", Name="Theme")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Theme : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Theme object.
        /// </summary>
        /// <param name="themeId">Initial value of the themeId property.</param>
        /// <param name="modified">Initial value of the modified property.</param>
        /// <param name="created">Initial value of the created property.</param>
        public static Theme CreateTheme(global::System.Int32 themeId, global::System.DateTime modified, global::System.DateTime created)
        {
            Theme theme = new Theme();
            theme.themeId = themeId;
            theme.modified = modified;
            theme.created = created;
            return theme;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 themeId
        {
            get
            {
                return _themeId;
            }
            set
            {
                if (_themeId != value)
                {
                    OnthemeIdChanging(value);
                    ReportPropertyChanging("themeId");
                    _themeId = StructuralObject.SetValidValue(value, "themeId");
                    ReportPropertyChanged("themeId");
                    OnthemeIdChanged();
                }
            }
        }
        private global::System.Int32 _themeId;
        partial void OnthemeIdChanging(global::System.Int32 value);
        partial void OnthemeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String thumbnailUrl
        {
            get
            {
                return _thumbnailUrl;
            }
            set
            {
                OnthumbnailUrlChanging(value);
                ReportPropertyChanging("thumbnailUrl");
                _thumbnailUrl = StructuralObject.SetValidValue(value, true, "thumbnailUrl");
                ReportPropertyChanged("thumbnailUrl");
                OnthumbnailUrlChanged();
            }
        }
        private global::System.String _thumbnailUrl;
        partial void OnthumbnailUrlChanging(global::System.String value);
        partial void OnthumbnailUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime modified
        {
            get
            {
                return _modified;
            }
            set
            {
                OnmodifiedChanging(value);
                ReportPropertyChanging("modified");
                _modified = StructuralObject.SetValidValue(value, "modified");
                ReportPropertyChanged("modified");
                OnmodifiedChanged();
            }
        }
        private global::System.DateTime _modified;
        partial void OnmodifiedChanging(global::System.DateTime value);
        partial void OnmodifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime created
        {
            get
            {
                return _created;
            }
            set
            {
                OncreatedChanging(value);
                ReportPropertyChanging("created");
                _created = StructuralObject.SetValidValue(value, "created");
                ReportPropertyChanged("created");
                OncreatedChanged();
            }
        }
        private global::System.DateTime _created;
        partial void OncreatedChanging(global::System.DateTime value);
        partial void OncreatedChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AppDataModel1", "FK_Website_Theme", "Website")]
        public EntityCollection<Website> Websites
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Website>("AppDataModel1.FK_Website_Theme", "Website");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Website>("AppDataModel1.FK_Website_Theme", "Website", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AppDataModel1", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="userId">Initial value of the userId property.</param>
        /// <param name="modified">Initial value of the modified property.</param>
        /// <param name="created">Initial value of the created property.</param>
        public static User CreateUser(global::System.Int32 userId, global::System.DateTime modified, global::System.DateTime created)
        {
            User user = new User();
            user.userId = userId;
            user.modified = modified;
            user.created = created;
            return user;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 userId
        {
            get
            {
                return _userId;
            }
            set
            {
                if (_userId != value)
                {
                    OnuserIdChanging(value);
                    ReportPropertyChanging("userId");
                    _userId = StructuralObject.SetValidValue(value, "userId");
                    ReportPropertyChanged("userId");
                    OnuserIdChanged();
                }
            }
        }
        private global::System.Int32 _userId;
        partial void OnuserIdChanging(global::System.Int32 value);
        partial void OnuserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String firstName
        {
            get
            {
                return _firstName;
            }
            set
            {
                OnfirstNameChanging(value);
                ReportPropertyChanging("firstName");
                _firstName = StructuralObject.SetValidValue(value, true, "firstName");
                ReportPropertyChanged("firstName");
                OnfirstNameChanged();
            }
        }
        private global::System.String _firstName;
        partial void OnfirstNameChanging(global::System.String value);
        partial void OnfirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lastName
        {
            get
            {
                return _lastName;
            }
            set
            {
                OnlastNameChanging(value);
                ReportPropertyChanging("lastName");
                _lastName = StructuralObject.SetValidValue(value, true, "lastName");
                ReportPropertyChanged("lastName");
                OnlastNameChanged();
            }
        }
        private global::System.String _lastName;
        partial void OnlastNameChanging(global::System.String value);
        partial void OnlastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true, "email");
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, true, "username");
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, true, "password");
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, true, "address");
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String city
        {
            get
            {
                return _city;
            }
            set
            {
                OncityChanging(value);
                ReportPropertyChanging("city");
                _city = StructuralObject.SetValidValue(value, true, "city");
                ReportPropertyChanged("city");
                OncityChanged();
            }
        }
        private global::System.String _city;
        partial void OncityChanging(global::System.String value);
        partial void OncityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String state
        {
            get
            {
                return _state;
            }
            set
            {
                OnstateChanging(value);
                ReportPropertyChanging("state");
                _state = StructuralObject.SetValidValue(value, true, "state");
                ReportPropertyChanged("state");
                OnstateChanged();
            }
        }
        private global::System.String _state;
        partial void OnstateChanging(global::System.String value);
        partial void OnstateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String zip
        {
            get
            {
                return _zip;
            }
            set
            {
                OnzipChanging(value);
                ReportPropertyChanging("zip");
                _zip = StructuralObject.SetValidValue(value, true, "zip");
                ReportPropertyChanged("zip");
                OnzipChanged();
            }
        }
        private global::System.String _zip;
        partial void OnzipChanging(global::System.String value);
        partial void OnzipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime modified
        {
            get
            {
                return _modified;
            }
            set
            {
                OnmodifiedChanging(value);
                ReportPropertyChanging("modified");
                _modified = StructuralObject.SetValidValue(value, "modified");
                ReportPropertyChanged("modified");
                OnmodifiedChanged();
            }
        }
        private global::System.DateTime _modified;
        partial void OnmodifiedChanging(global::System.DateTime value);
        partial void OnmodifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime created
        {
            get
            {
                return _created;
            }
            set
            {
                OncreatedChanging(value);
                ReportPropertyChanging("created");
                _created = StructuralObject.SetValidValue(value, "created");
                ReportPropertyChanged("created");
                OncreatedChanged();
            }
        }
        private global::System.DateTime _created;
        partial void OncreatedChanging(global::System.DateTime value);
        partial void OncreatedChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AppDataModel1", "FK_UserRoles_Users", "UserRoles")]
        public EntityCollection<UserRole> UserRoles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserRole>("AppDataModel1.FK_UserRoles_Users", "UserRoles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserRole>("AppDataModel1.FK_UserRoles_Users", "UserRoles", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AppDataModel1", Name="UserRole")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserRole : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserRole object.
        /// </summary>
        /// <param name="userRoleId">Initial value of the userRoleId property.</param>
        public static UserRole CreateUserRole(global::System.Int32 userRoleId)
        {
            UserRole userRole = new UserRole();
            userRole.userRoleId = userRoleId;
            return userRole;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 userRoleId
        {
            get
            {
                return _userRoleId;
            }
            set
            {
                if (_userRoleId != value)
                {
                    OnuserRoleIdChanging(value);
                    ReportPropertyChanging("userRoleId");
                    _userRoleId = StructuralObject.SetValidValue(value, "userRoleId");
                    ReportPropertyChanged("userRoleId");
                    OnuserRoleIdChanged();
                }
            }
        }
        private global::System.Int32 _userRoleId;
        partial void OnuserRoleIdChanging(global::System.Int32 value);
        partial void OnuserRoleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> userId
        {
            get
            {
                return _userId;
            }
            set
            {
                OnuserIdChanging(value);
                ReportPropertyChanging("userId");
                _userId = StructuralObject.SetValidValue(value, "userId");
                ReportPropertyChanged("userId");
                OnuserIdChanged();
            }
        }
        private Nullable<global::System.Int32> _userId;
        partial void OnuserIdChanging(Nullable<global::System.Int32> value);
        partial void OnuserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> roleId
        {
            get
            {
                return _roleId;
            }
            set
            {
                OnroleIdChanging(value);
                ReportPropertyChanging("roleId");
                _roleId = StructuralObject.SetValidValue(value, "roleId");
                ReportPropertyChanged("roleId");
                OnroleIdChanged();
            }
        }
        private Nullable<global::System.Int32> _roleId;
        partial void OnroleIdChanging(Nullable<global::System.Int32> value);
        partial void OnroleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> modified
        {
            get
            {
                return _modified;
            }
            set
            {
                OnmodifiedChanging(value);
                ReportPropertyChanging("modified");
                _modified = StructuralObject.SetValidValue(value, "modified");
                ReportPropertyChanged("modified");
                OnmodifiedChanged();
            }
        }
        private Nullable<global::System.DateTime> _modified;
        partial void OnmodifiedChanging(Nullable<global::System.DateTime> value);
        partial void OnmodifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> created
        {
            get
            {
                return _created;
            }
            set
            {
                OncreatedChanging(value);
                ReportPropertyChanging("created");
                _created = StructuralObject.SetValidValue(value, "created");
                ReportPropertyChanged("created");
                OncreatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _created;
        partial void OncreatedChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AppDataModel1", "FK_UserRoles_Roles", "Roles")]
        public Role Role
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("AppDataModel1.FK_UserRoles_Roles", "Roles").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("AppDataModel1.FK_UserRoles_Roles", "Roles").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Role> RoleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("AppDataModel1.FK_UserRoles_Roles", "Roles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Role>("AppDataModel1.FK_UserRoles_Roles", "Roles", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AppDataModel1", "FK_UserRoles_Users", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("AppDataModel1.FK_UserRoles_Users", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("AppDataModel1.FK_UserRoles_Users", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("AppDataModel1.FK_UserRoles_Users", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("AppDataModel1.FK_UserRoles_Users", "Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AppDataModel1", Name="Website")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Website : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Website object.
        /// </summary>
        /// <param name="websiteId">Initial value of the websiteId property.</param>
        /// <param name="themeId">Initial value of the themeId property.</param>
        /// <param name="active">Initial value of the active property.</param>
        /// <param name="enableAds">Initial value of the enableAds property.</param>
        /// <param name="modified">Initial value of the modified property.</param>
        /// <param name="created">Initial value of the created property.</param>
        public static Website CreateWebsite(global::System.Int32 websiteId, global::System.Int32 themeId, global::System.Byte active, global::System.Byte enableAds, global::System.DateTime modified, global::System.DateTime created)
        {
            Website website = new Website();
            website.websiteId = websiteId;
            website.themeId = themeId;
            website.active = active;
            website.enableAds = enableAds;
            website.modified = modified;
            website.created = created;
            return website;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 websiteId
        {
            get
            {
                return _websiteId;
            }
            set
            {
                if (_websiteId != value)
                {
                    OnwebsiteIdChanging(value);
                    ReportPropertyChanging("websiteId");
                    _websiteId = StructuralObject.SetValidValue(value, "websiteId");
                    ReportPropertyChanged("websiteId");
                    OnwebsiteIdChanged();
                }
            }
        }
        private global::System.Int32 _websiteId;
        partial void OnwebsiteIdChanging(global::System.Int32 value);
        partial void OnwebsiteIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String domain
        {
            get
            {
                return _domain;
            }
            set
            {
                OndomainChanging(value);
                ReportPropertyChanging("domain");
                _domain = StructuralObject.SetValidValue(value, true, "domain");
                ReportPropertyChanged("domain");
                OndomainChanged();
            }
        }
        private global::System.String _domain;
        partial void OndomainChanging(global::System.String value);
        partial void OndomainChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true, "title");
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String slogan
        {
            get
            {
                return _slogan;
            }
            set
            {
                OnsloganChanging(value);
                ReportPropertyChanging("slogan");
                _slogan = StructuralObject.SetValidValue(value, true, "slogan");
                ReportPropertyChanged("slogan");
                OnsloganChanged();
            }
        }
        private global::System.String _slogan;
        partial void OnsloganChanging(global::System.String value);
        partial void OnsloganChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String logoUrl
        {
            get
            {
                return _logoUrl;
            }
            set
            {
                OnlogoUrlChanging(value);
                ReportPropertyChanging("logoUrl");
                _logoUrl = StructuralObject.SetValidValue(value, true, "logoUrl");
                ReportPropertyChanged("logoUrl");
                OnlogoUrlChanged();
            }
        }
        private global::System.String _logoUrl;
        partial void OnlogoUrlChanging(global::System.String value);
        partial void OnlogoUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> homePageId
        {
            get
            {
                return _homePageId;
            }
            set
            {
                OnhomePageIdChanging(value);
                ReportPropertyChanging("homePageId");
                _homePageId = StructuralObject.SetValidValue(value, "homePageId");
                ReportPropertyChanged("homePageId");
                OnhomePageIdChanged();
            }
        }
        private Nullable<global::System.Int32> _homePageId;
        partial void OnhomePageIdChanging(Nullable<global::System.Int32> value);
        partial void OnhomePageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String adsenseId
        {
            get
            {
                return _adsenseId;
            }
            set
            {
                OnadsenseIdChanging(value);
                ReportPropertyChanging("adsenseId");
                _adsenseId = StructuralObject.SetValidValue(value, true, "adsenseId");
                ReportPropertyChanged("adsenseId");
                OnadsenseIdChanged();
            }
        }
        private global::System.String _adsenseId;
        partial void OnadsenseIdChanging(global::System.String value);
        partial void OnadsenseIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String googleAnalyticsId
        {
            get
            {
                return _googleAnalyticsId;
            }
            set
            {
                OngoogleAnalyticsIdChanging(value);
                ReportPropertyChanging("googleAnalyticsId");
                _googleAnalyticsId = StructuralObject.SetValidValue(value, true, "googleAnalyticsId");
                ReportPropertyChanged("googleAnalyticsId");
                OngoogleAnalyticsIdChanged();
            }
        }
        private global::System.String _googleAnalyticsId;
        partial void OngoogleAnalyticsIdChanging(global::System.String value);
        partial void OngoogleAnalyticsIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 themeId
        {
            get
            {
                return _themeId;
            }
            set
            {
                OnthemeIdChanging(value);
                ReportPropertyChanging("themeId");
                _themeId = StructuralObject.SetValidValue(value, "themeId");
                ReportPropertyChanged("themeId");
                OnthemeIdChanged();
            }
        }
        private global::System.Int32 _themeId;
        partial void OnthemeIdChanging(global::System.Int32 value);
        partial void OnthemeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte active
        {
            get
            {
                return _active;
            }
            set
            {
                OnactiveChanging(value);
                ReportPropertyChanging("active");
                _active = StructuralObject.SetValidValue(value, "active");
                ReportPropertyChanged("active");
                OnactiveChanged();
            }
        }
        private global::System.Byte _active;
        partial void OnactiveChanging(global::System.Byte value);
        partial void OnactiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte enableAds
        {
            get
            {
                return _enableAds;
            }
            set
            {
                OnenableAdsChanging(value);
                ReportPropertyChanging("enableAds");
                _enableAds = StructuralObject.SetValidValue(value, "enableAds");
                ReportPropertyChanged("enableAds");
                OnenableAdsChanged();
            }
        }
        private global::System.Byte _enableAds;
        partial void OnenableAdsChanging(global::System.Byte value);
        partial void OnenableAdsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime modified
        {
            get
            {
                return _modified;
            }
            set
            {
                OnmodifiedChanging(value);
                ReportPropertyChanging("modified");
                _modified = StructuralObject.SetValidValue(value, "modified");
                ReportPropertyChanged("modified");
                OnmodifiedChanged();
            }
        }
        private global::System.DateTime _modified;
        partial void OnmodifiedChanging(global::System.DateTime value);
        partial void OnmodifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime created
        {
            get
            {
                return _created;
            }
            set
            {
                OncreatedChanging(value);
                ReportPropertyChanging("created");
                _created = StructuralObject.SetValidValue(value, "created");
                ReportPropertyChanged("created");
                OncreatedChanged();
            }
        }
        private global::System.DateTime _created;
        partial void OncreatedChanging(global::System.DateTime value);
        partial void OncreatedChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AppDataModel1", "FK_Menu_Website", "Menu")]
        public EntityCollection<Menu> Menus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Menu>("AppDataModel1.FK_Menu_Website", "Menu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Menu>("AppDataModel1.FK_Menu_Website", "Menu", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AppDataModel1", "FK_Page_Website", "Page")]
        public EntityCollection<Page> Pages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Page>("AppDataModel1.FK_Page_Website", "Page");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Page>("AppDataModel1.FK_Page_Website", "Page", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AppDataModel1", "FK_Website_Theme", "Theme")]
        public Theme Theme
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theme>("AppDataModel1.FK_Website_Theme", "Theme").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theme>("AppDataModel1.FK_Website_Theme", "Theme").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Theme> ThemeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theme>("AppDataModel1.FK_Website_Theme", "Theme");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Theme>("AppDataModel1.FK_Website_Theme", "Theme", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
