//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SO.SilList.CodeGeneration.DbContexts.SilList
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public Site()
        {
            this.BusinessCategoryTypes = new HashSet<BusinessCategoryType>();
            this.Businesses = new HashSet<Business>();
            this.Members = new HashSet<Member>();
            this.Rentals = new HashSet<Rental>();
        }
    
        public int siteId { get; set; }
        public string name { get; set; }
        public string domain { get; set; }
    
        public virtual ICollection<BusinessCategoryType> BusinessCategoryTypes { get; set; }
        public virtual ICollection<Business> Businesses { get; set; }
        public virtual ICollection<Member> Members { get; set; }
        public virtual ICollection<Rental> Rentals { get; set; }
    }
}
