//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SO.SilList.CodeGeneration.DbContexts.SilList
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.JobCategories = new HashSet<JobCategory>();
        }
    
        public System.Guid jobId { get; set; }
        public System.Guid listingDetailId { get; set; }
        public Nullable<int> siteId { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<int> jobTypeId { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public Nullable<bool> isTravelRequired { get; set; }
        public Nullable<bool> isTelecomute { get; set; }
        public Nullable<System.Guid> jobCompanyId { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<int> modifiedBy { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual ICollection<JobCategory> JobCategories { get; set; }
        public virtual JobType JobType { get; set; }
    }
}
